config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get "login" , to: "session#new"
  post "login" , to: "session#create"
  delete "logout" , to: "session#destroy"
  post "message" , to: "message#create"
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  include ApplicationHelper
  before_action :require_login , only: [:index]
  def index
    @messages = Message.all
    @users = User.all
    @message = Message.new
  end

  private
   def require_login
      unless is_loggedin?
        redirect_to login_path
      end
    end


end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  include ApplicationHelper
  before_action :require_login , only: [:create]
  def create
    @message = Message.new(chatroom_params)
    @message.user_id = session[:user_id]
    if @message.save
      ActionCable.server.broadcast "chatroom_channel",
                                   mod_message: message_render(@message)
      # redirect_to root_path
    else
      flash[:danger] = "Invalid message data"
      redirect_to root_path , status: 401
    end
  end


  private
  def chatroom_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'layouts/message', locals: { data: message, show_details: true  })
  end
  def require_login
    unless is_loggedin?
      redirect_to login_path
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  before_action :log_in_redirect, only: [:create, :new, ]
  def create
    username = params[:session][:username]
    password = params[:session][:password]
    user = User.find_by(username: username)
    if user && user.authenticate(password)
       session[:user_id] = user.id
       flash[:success] = "Welcome back, #{user.username}!"
       redirect_to root_path
    else
      flash[:danger] = 'Invalid username or password'
      render 'new', status: 401
    end
  end

  def new

  end

  def destroy
    session[:user_id] = nil
    flash.now[:notice] = "User logout"
    redirect_to login_path
  end
  
  private
  def log_in_redirect
    if session[:user_id]
    flash[:notice] = "You are already logged in!"
    redirect_to root_path
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_loggedin?
    session[:user_id]
  end

  def current_user
    if session[:user_id]
      @current_user = User.find_by(id: session[:user_id])
    end
  end
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned icon header">
  <i class="circular users icon yellow"></i>
  Say Something
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid card chat-box">
      <div class="content chat-box-body" id="message-list-container">
        <% @messages.each do |message| %>
          <%= render :partial=>'layouts/message', locals: { data: message, show_details: true } %>
        <% end %>
      </div>
      <div class="extra content chat-footer">
        <%= form_for(@message, url: message_path, remote: true) do |f| %>
          <div class="ui input fluid">
            <%= f.text_field :body, placeholder:"Say something..." %>
            <%= button_to raw("<i class=\"paper plane icon\"></i>"),
                          message_path,
                          class: "ui icon button yellow" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid card chat-box">
      <div class="content">
        <div class="ui vertical fluid menu">
          <a class="active item">
            Users
          </a>
          <% @users.each do |user| %>
            <a class="item">
              <%= user.username %>
            </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'danger' %>
    <div class="ui negative message transition">
      <i class="close icon"></i>
      <div class="header">
        Error:
      </div>
      <p><%= msg %></p>
    </div>
  <% end %>
  <% if type == 'success' %>
    <div class="ui success message transition">
      <i class="close icon"></i>
      <div class="header">
        Success:
      </div>
      <p><%= msg %></p>
    </div>
  <% end %>

  <% if type == 'notice' %>
    <div class="ui blue message transition">
      <i class="close icon"></i>
      <div class="header">
        Notice:
      </div>
      <p><%= msg %></p>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<div class="ui inverted  menu">
  <div class="ui container">
    <a class="item">
      Home
    </a>
    <a class="item">
      Messages
    </a>
    <a class="item active">
      Friends
    </a>
    <div class="right menu">
      <%= link_to "Logout", logout_path, class: 'ui item', data: { "turbo-method": :delete } %>
    </div>
  </div>
</div>

app/views/layouts/_message.html.erb
<div class="message-box-container fluid">
  <div class="message-box">

    <div class="message-header">
      <%= data.user.username %>
    </div>

    <p class="message-text"><%= data.body %></p>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageMe</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "layouts/header" %>
<div class="ui container">
  <%= render "layouts/flash" %>
  <%= yield %>
</div>
</body>
</html>

app/views/session/new.html.erb
<h1 class="ui center aligned icon header">
  Welcome to message me
</h1>

<h4 class="ui center aligned icon header">
  Login to continue
</h4>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for( :session, url: login_path) do |f| %>
        <div class="ui form">
          <div class="field">
            <label><%= f.label :username , "Username" %></label>
            <div class="ui left icon input">
              <%= f.text_field :username , placeholder: "Username" %>
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <label><%= f.label :password , "Password" %></label>
            <div class="ui left icon input">
              <%= f.password_field :password , placeholder: "Password" %>
              <i class="lock icon"></i>
            </div>
          </div>
          <%= f.submit "Login" , class:'ui blue submit button' %>
        </div>
      <% end %>
    </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>